version: 2
run:
  timeout: 5m
linters:
  disable-all: true
  enable:
    - funlen
    - gocognit
    - cyclop
    - nestif
    - gocyclo
    - dupl
linters-settings:
  funlen:
    lines: 100
    statements: 50
  gocognit:
    min-complexity: 30
  nestif:
    min-complexity: 5
